### ISSUE TITLE
Golint complains about not commented functions in test

### ISSUE THREAD

**Issue by xfix** [codeclimate-community/codeclimate-golint#10]
If I have a file called `whatever_test.go` and have a function in it like this:

``` go
package whatever

func TestWhatever(t *testing.T) {
}
```

Code Climate complains about lack of comment for "exported" function `TestWhatever`. This doesn't happen in standard command line version of golint, which ignores tests.

**Comment by ABaldwinHunter** [comment]
Hey @xfix! Thanks for reaching out about that issue.

I think you bring up a good point, and we can action work to fix this issue.

In the meantime, you have a couple of good workaround options for excluding those files in your `.codeclimate.yml` like so:

1) Option 1 - exclude from all engines
```yaml
---
engines:
  golint:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_paths:
- "**_test.go"
```

2) Option 2 - only exclude from `codeclimate-golint`

```yaml
---
engines:
  golint:
    enabled: true
    exclude_paths:
    - "**_test.go"
ratings:
  paths:
    - "**.go"
exclude_paths: []
```
